trigger:
- master

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'
  demands:
    - npm

variables:
- group: SpaceGameVars
- group: FWD-Secrets

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- script: 'echo Publish variables called from group--- dotnetSdkVersion is $(dotnetSdkVersion)-- wwwrootDir is $(wwwrootDir) -- buildConfiguration is $(buildConfiguration) --- vault items FWD-DB-UNAME is $(FWD-DB-UNAME) --- FWD-DB-PASSWORD is $(FWD-DB-PASSWORD)'
  displayName: 'Group Vars and Vault Testing...'

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compile Sass assets'


- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: $(wwwrootDir)

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: $(buildConfiguration)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()
